### ISSUE TITLE
[Bug] 在lobe chat的插件中添加代理配置，在插件中无法获取MIDJOURNEY_PROXY_URL值，导致插件报错。

### ISSUE THREAD

**Issue by michaej** [lobehub/chat-plugin-midjourney#16]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/lobe-midjourney-webui/assets/13174278/afef6fc1-0298-4f7a-ad4b-765250fc5640)

**Comment by arvinxx** [comment]
已经修复了
