### ISSUE TITLE
MJ插件在midjourney-webui.lobehub.com可以使用，但是在lobechat插件里无法启用[Bug] 

### ISSUE THREAD

**Issue by wangshipei** [lobehub/chat-plugin-midjourney#17]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

MJ插件在midjourney-webui.lobehub.com可以使用，但是在lobechat插件里无法启用

**Comment by wangshipei** [comment]
![mj](https://github.com/lobehub/lobe-midjourney-webui/assets/54164572/e82b6d70-27e0-414a-85aa-0bec42511232)
在lobechat里，插件可以调用，但是无法画出图片，在midjourney-webui.lobehub.com这个网站可以画图出图片

**Comment by woxiqingxian** [comment]
遇到同样的问题。
查看 lobechat 发出去的请求有一个请求 错误了，
该请求如下：发现 header 里面请求 x-midjourney-proxy-url 是一个空字符串，但是已经配置好了 mj-proxy 链接
在终端模拟，然后header 写入 x-midjourney-proxy-url  为指定 mj-proxy 就可以跑了。
说明 lobechat 在构建的时候  x-midjourney-proxy-url  出错了。
麻烦帮跟进一下，十分感谢。
@lobehubbot 

```
curl 'https://midjourney.chat-plugin.lobehub.com/api/midjourney?path=%2Fmj%2Fsubmit%2Fimagine' \
  -H 'authority: midjourney.chat-plugin.lobehub.com' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://midjourney.chat-plugin.lobehub.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://midjourney.chat-plugin.lobehub.com/iframe' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  -H 'x-midjourney-proxy-url: ;' \
  --data-raw '{"prompt":" child playing with colorful balloons in a sunny park, joyful expression, vibrant colors, green grass, blue sky --v 6"}'
```

**Comment by arvinxx** [comment]
嗯，一个已知 bug，今天修复哈~

**Comment by arvinxx** [comment]
已经修复了 @woxiqingxian @wangshipei  各位可以试试看哈

**Comment by woxiqingxian** [comment]
@arvinxx 刚刚测试了一下，那个 x-midjourney-proxy-url 是有带上了。但是请求还是失败，返回 error code: 1016。
使用的是 lobechat 最新版本，docker 部署

现在假设我给的 proxy 地址是：https://x.abc.com 然后 x-midjourney-proxy-url  带的变成了 https://x-proxy.abc.com

**Comment by arvinxx** [comment]
咦，我晚上研究下
