### ISSUE TITLE
修改翻译

### ISSUE THREAD

**Issue by ifsheldon** [lobehub/chat-plugin-midjourney#2]
https://github.com/lobehub/chat-plugin-midjourney/blob/93a93e72f59075018de6e7389ca4a729f0f2a368/src/features/Preview/ImagineAction.tsx#L107

这里把 variation 翻译成 ”风格化“ 应该不是很准确，这样容易和 ”stylize“ 这个参数弄混了。建议改成”变体“。

**Comment by arvinxx** [comment]
收到，我们先改成英文了
