### ISSUE TITLE
[Question] 配置代理提示404

### ISSUE THREAD

**Issue by seekme-ai** [lobehub/chat-plugin-midjourney#30]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/lobehub/lobe-midjourney-webui/assets/8808091/301b12a7-09e7-464a-9019-c1d02702889d)

**Comment by seekme-ai** [comment]
而且也没有配置秘钥的地方

**Comment by seekme-ai** [comment]
已解决

**Comment by SmallAi-API** [comment]
如何解决的？> 已解决
